apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 8888
    targetPort: 80
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: svc-wp
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: svc-sql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP