apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    version: "1"
    app: "wordpress"
spec:
  containers:
  - image: wordpress:latest
    imagePullPolicy: IfNotPresent
    name: wordpress
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    livenessProbe: 
      exec:
        command:
        - cat
        - readme.html
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 2 
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 2    
    env:
    - name: WORDPRESS_DB_HOST
      valueFrom:
        secretKeyRef:
          key: db_host
          name: mysql-secret
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          key: db_name
          name: mysql-secret
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
         key: user
         name: mysql-secret
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: user_pwd
          name: mysql-secret            

      